In [11]:
import os 
import torch
import numpy as np
# import torchvision
import pandas as pd

from local_dataset_utilities import download_dataset,load_dataset_into_to_dataframe,partition_dataset


#### 1. Loading Dataset

In [5]:
download_dataset()

100% | 80.23 MB | 3.25 MB/s | 24.70 sec elapsed

In [8]:
df = load_dataset_into_to_dataframe()
df.head()

100%|██████████| 50000/50000 [00:52<00:00, 957.17it/s] 

Class distribution: [25000 25000]


text  label
0  I went and saw this movie last night after bei...      1
0  Actor turned director Bill Paxton follows up h...      1
0  As a recreational golfer with some knowledge o...      1
0  I saw this film in a sneak preview, and it is ...      1
0  Bill Paxton has taken the true story of the 19...      1

In [ ]:
df.iloc[0].text

"I went and saw this movie last night after being coaxed to by a few friends of mine. I'll admit that I was reluctant to see it because from what I knew of Ashton Kutcher he was only able to do comedy. I was wrong. Kutcher played the character of Jake Fischer very well, and Kevin Costner played Ben Randall with such professionalism. The sign of a good movie is that it can toy with our emotions. This one did exactly that. The entire theater (which was sold out) was overcome by laughter during the first half of the movie, and were moved to tears during the second half. While exiting the theater I not only saw many women in tears, but many full grown men as well, trying desperately not to let anyone see them crying. This movie was great, and I suggest that you go see it before you judge."

In [10]:
np.bincount(df.label)

array([25000, 25000])

In [12]:
partition_dataset(df)

In [18]:
df_train = pd.read_csv("train.csv")
df_train.tail()

# np.bincount(df_train['label'])

index                                               text  label
34995      0  Frank Capra's creativity must have been just a...      0
34996      0  Just saw the film tonight in a preview and it'...      0
34997      0  If you love Japanese monster movies, you'll lo...      1
34998      0  Because it came from HBO and based on the IMDb...      0
34999      0  WARNING!!! SOME POSSIBLE PLOT SPOILERS, AS IF ...      0

In [23]:
df_val = pd.read_csv("val.csv")
df_val.tail()
# np.bincount(df_val.label)

index                                               text  label
4995      0  The Matador is a strange film. Its main charac...      1
4996      0  Not bad performances. Whoopi plays the wise/wa...      0
4997      0  I was surprised when I saw this film. I'd hear...      0
4998      0  When great director/actor combinations are tal...      0
4999      0  This show is non Stop hilarity. the first joke...      1

In [24]:
df_test = pd.read_csv("test.csv")
df_test.tail()
# np.bincount(df_test.label)

index                                               text  label
9995      0  Every generation fully believes it is living i...      0
9996      0  Possibly the most brilliant thing about Che: P...      1
9997      0  I was unsure of this movie before renting and ...      1
9998      0  Just got out of an advance screening, and wow ...      1
9999      0  I sense out there a mix of confusion and varyi...      1

#### 2) Bag-of-words model

In [26]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
cv = CountVectorizer(lowercase=True,max_features=10_000,stop_words="english")


CountVectorizer(max_features=10000, stop_words='english')

In [29]:
cv.fit(df_train.text)

CountVectorizer(max_features=10000, stop_words='english')

In [32]:
cv.vocabulary_

{'started': np.int64(8515),
 'watching': np.int64(9725),
 'series': np.int64(7955),
 'cable': np.int64(1322),
 'idea': np.int64(4485),
 'hate': np.int64(4188),
 'character': np.int64(1545),
 'hold': np.int64(4336),
 'beautifully': np.int64(894),
 'developed': np.int64(2574),
 'understand': np.int64(9376),
 'react': np.int64(7192),
 'frustration': np.int64(3738),
 'fear': np.int64(3438),
 'greed': np.int64(4020),
 'temptation': np.int64(8973),
 'way': np.int64(9735),
 'viewer': np.int64(9575),
 'experiencing': np.int64(3279),
 'christopher': np.int64(1658),
 'learning': np.int64(5197),
 'br': np.int64(1153),
 'abuse': np.int64(189),
 'physically': np.int64(6605),
 'emotionally': np.int64(3046),
 'just': np.int64(4961),
 'read': np.int64(7195),
 'newspaper': np.int64(6086),
 'women': np.int64(9880),
 'tolerate': np.int64(9133),
 'behavior': np.int64(917),
 'dream': np.int64(2831),
 'house': np.int64(4415),
 'endless': np.int64(3074),
 'supply': np.int64(8779),
 'expensive': np.int64(3275

In [33]:
X_train = cv.transform(df_train.text)
X_val = cv.transform(df_val.text)
X_test = cv.transform(df_test.text)

In [35]:
X_train.shape 

# (35000, 10000) ==> len(X_train dataset),len(Vocabulary)

(35000, 10000)

In [36]:
type(X_train)

scipy.sparse._csr.csr_matrix

In [38]:
feature_vector = np.array(X_train[0].todense())[0]

In [39]:
feature_vector

array([0, 0, 0, ..., 0, 0, 0], shape=(10000,))

In [40]:
np.bincount(feature_vector)

array([9926,   67,    5,    0,    1,    0,    1])